### ISSUE TITLE
Using a decimal in HFOV setting

### ISSUE THREAD

**Issue by jesseking3** [YellowFive5/OneHundredAndEighty#2]
Setting HFOV using a decimal setting works, but after exiting and restarting, the app no longer starts. 

Is that HFOV truly looking for HFOV or overall DFOV?

__

Diagonal Field of View (FOV) | 78°
Horizontal Field of View (FOV) | 70.42°
Vertical Field of View (FOV) | 43.3°

**Comment by YellowFive5** [comment]
Don't use decimal. Use integer value of HFOV - 70 in your case. This type of precision is overhead

**Comment by YellowFive5** [comment]
But I think it's good idea to change type to decimal. I'll do this. Thanks.

**Comment by YellowFive5** [comment]
Done!
