### ISSUE TITLE
camera setup issue

### ISSUE THREAD

**Issue by chunleiguo** [YellowFive5/OneHundredAndEighty#3]
dear Eugene,
I find that my laptop can't support 4 cams working simultaneously in 720p resolution. 
I'd like to know if your program can work correctly with 2 cameras in 720p and another 2 cameras in 640x360, or if it is okay when I let all the 4 cameras in 640x360 ? which plan is better for me? 

Best regards

**Comment by YellowFive5** [comment]
I think using 4 cameras with different resolutions is not a good idea at all. 
You can try to setup all with 640x360 - but I think this resolution is not enought for acceptable detection accuracy

**Comment by chunleiguo** [comment]
Got it, thanks a lot.
